# This is a basic workflow to help you get started with Actions

name: CI - test conda environmnet

# Controls when the action will run. 
on:
  # Triggers the workflow on pull request events for master
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-run:
    name: Try conda environment with "envs/python3.8env.yml"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.8.8"]
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: envs/python3.8env.yml
          auto-activate-base: true
          activate-environment: true
          python-version: ${{ matrix.python-version }}
      - name: Conda info
        run: |
          conda info
          which python
          conda list
