name: Test conda environment

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master]
  pull_request:
    branches: [ master, github-actions ]

jobs:
  build-and-run:
    name: Create conda environment with "envs/python3.8env.yml"
    if: ${{ github.repository == 'slaclab/pythonEnvs' }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.8.8"]
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: envs/python3.8env.yml
          auto-activate-base: true
          activate-environment: true
          python-version: ${{ matrix.python-version }}
      - name: Conda info
        run: |
          conda info
          which python
          conda list
