name: Create and Test environment

on:
 push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-run:
    name: Create conda environment with "envs/python3.8env.yml"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.8.8"]
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: true
          activate-environment: true
          conda-build-version: 4.10.1
          python-version: ${{ matrix.python-version }}
          conda-channels: conda-forge
      - name: Conda info
        run: |
          conda info
          which python
      - name: Conda create environment
        run: |
          - conda env create -q -n env-test -f envs/python3.8env.yml